### ISSUE TITLE
startPageForReviews missing in the input

### ISSUE THREAD

**Issue by abhay-kum** [epctex/yelp-scraper#1]
Hi,

Could you add parameter like startPageForReview in input payload.

Suppose i want to scrape incremental review of the particular restaurant. i will scrape first 50 and then check with our date scraped if its greater than then i will request for after 50 reviews .

**Comment by tugkan** [comment]
Hey @abhay-kum ! 

Thank you very much for reaching out and letting us know about your inquiry. We just deployed a new version where this functionality is implemented successfully. Please use the latest version for the best experience!

Best
